from __future__ import annotations

from typing import IO, Iterator, Literal, Protocol, runtime_checkable

SwapMode = Literal["full_refresh", "partition_overwrite"]


@runtime_checkable
class StorageBackend(Protocol):
    def join_paths(self, root: str, *segments: str) -> str: ...
    def path_parent(self, path: str) -> str: ...
    def path_basename(self, path: str) -> str: ...
    def path_with_suffix(self, path: str, suffix: str) -> str: ...
    def path_normalize(self, path: str) -> str: ...

    def path_exists(self, path: str) -> bool: ...
    def path_is_dir(self, path: str) -> bool: ...
    def path_mkdir(
        self, path: str, *, parents: bool = True, exist_ok: bool = True
    ) -> None: ...
    def path_listdir(self, path: str) -> list[str]: ...
    def path_glob(self, base: str, pattern: str) -> list[str]: ...
    def path_rglob(self, base: str, pattern: str) -> list[str]: ...
    def path_content_length(self, path: str) -> int: ...
    def path_read_bytes(self, path: str) -> bytes: ...
    def path_write_bytes(
        self, path: str, data: bytes, *, atomic: bool = True
    ) -> None: ...
    def path_open_for_append(
        self, path: str, encoding: str = "utf-8"
    ) -> Iterator[IO[str]]: ...
    def path_replace(self, src: str, dst: str) -> None: ...
    def path_delete_tree(self, path: str) -> None: ...

    def staging_swap_atomic(
        self,
        *,
        staging_path: str,
        target_path: str,
        mode: SwapMode,
    ) -> None: ...
