"""Connector families for ingestion runtimes."""

from elt_pipeline.ingest.connectors.broker_kafka import BrokerKafkaConnector
from elt_pipeline.ingest.connectors.kafka import (
    KafkaConnectorBase,
    KafkaConnectorConfig,
    KafkaMessage,
    KafkaRunResult,
    KafkaStartingPosition,
)
from elt_pipeline.ingest.connectors.local_kafka import LocalKafkaConnector
from elt_pipeline.ingest.connectors.local_object_storage import LocalObjectStorageConnector
from elt_pipeline.ingest.connectors.local_rest import LocalRestConnector
from elt_pipeline.ingest.connectors.local_sql import LocalSqlConnector
from elt_pipeline.ingest.connectors.object_storage import (
    ObjectStorageConnectorBase,
    ObjectStorageConnectorConfig,
    ObjectStorageObject,
    ObjectStorageRunResult,
    ObjectStorageSyncMode,
)
from elt_pipeline.ingest.connectors.registry import (
    ConnectorFactory,
    ConnectorFamily,
    ConnectorFamilyUnsupportedError,
    ConnectorManifest,
    ConnectorPreset,
    ConnectorRegistryError,
    apply_connector_preset_defaults,
    get_connector_factory,
    is_connector_factory_registered,
    load_connector_manifest_from_json,
    load_connector_manifest_from_yaml,
    register_connector_factory,
)
from elt_pipeline.ingest.connectors.rest import (
    RestAuthConfig,
    RestAuthStrategy,
    RestConnectorBase,
    RestConnectorConfig,
    RestPaginationConfig,
    RestPaginationMode,
    RestPreparedRequest,
    RestRequestTemplate,
    RestRequestWindow,
    RestResolvedAuth,
    RestResponse,
    RestRetryPolicy,
    RestRunResult,
)
from elt_pipeline.ingest.connectors.sql import (
    SqlConnectionConfig,
    SqlConnectionDriver,
    SqlConnectorBase,
    SqlConnectorConfig,
    SqlDbConnection,
    SqlDbDriver,
    SqlExtractionMode,
    SqlPreparedQuery,
    SqlQueryResult,
    SqlQueryTemplate,
    SqlRunResult,
    SqlWatermarkConfig,
    SqlWatermarkSource,
    _build_db_driver,
)

__all__ = [
    "BrokerKafkaConnector",
    "KafkaConnectorBase",
    "KafkaConnectorConfig",
    "KafkaMessage",
    "KafkaRunResult",
    "KafkaStartingPosition",
    "LocalKafkaConnector",
    "LocalObjectStorageConnector",
    "RestAuthConfig",
    "RestAuthStrategy",
    "RestConnectorBase",
    "RestConnectorConfig",
    "RestPaginationConfig",
    "RestPaginationMode",
    "RestPreparedRequest",
    "RestRetryPolicy",
    "RestRequestTemplate",
    "RestRequestWindow",
    "RestResolvedAuth",
    "RestResponse",
    "RestRunResult",
    "LocalRestConnector",
    "LocalSqlConnector",
    "ObjectStorageConnectorBase",
    "ObjectStorageConnectorConfig",
    "ObjectStorageObject",
    "ObjectStorageRunResult",
    "ObjectStorageSyncMode",
    "SqlConnectionConfig",
    "SqlConnectionDriver",
    "SqlConnectorBase",
    "SqlConnectorConfig",
    "SqlDbConnection",
    "SqlDbDriver",
    "SqlExtractionMode",
    "SqlPreparedQuery",
    "SqlQueryResult",
    "SqlQueryTemplate",
    "SqlRunResult",
    "SqlWatermarkConfig",
    "SqlWatermarkSource",
    "_build_db_driver",
    "ConnectorFamily",
    "ConnectorFactory",
    "ConnectorManifest",
    "ConnectorPreset",
    "ConnectorRegistryError",
    "ConnectorFamilyUnsupportedError",
    "apply_connector_preset_defaults",
    "get_connector_factory",
    "is_connector_factory_registered",
    "load_connector_manifest_from_json",
    "load_connector_manifest_from_yaml",
    "register_connector_factory",
]
