"""Connector families for ingestion runtimes."""

from elt_pipeline.ingest.connectors.local_rest import LocalRestConnector
from elt_pipeline.ingest.connectors.local_sql import LocalSqlConnector
from elt_pipeline.ingest.connectors.rest import (
    RestAuthConfig,
    RestAuthStrategy,
    RestConnectorBase,
    RestConnectorConfig,
    RestPaginationConfig,
    RestPaginationMode,
    RestPreparedRequest,
    RestRequestTemplate,
    RestRequestWindow,
    RestResolvedAuth,
    RestResponse,
    RestRetryPolicy,
    RestRunResult,
)
from elt_pipeline.ingest.connectors.sql import (
    SqlConnectionConfig,
    SqlConnectionDriver,
    SqlConnectorBase,
    SqlConnectorConfig,
    SqlExtractionMode,
    SqlPreparedQuery,
    SqlQueryResult,
    SqlQueryTemplate,
    SqlRunResult,
    SqlWatermarkConfig,
    SqlWatermarkSource,
)

__all__ = [
    "RestAuthConfig",
    "RestAuthStrategy",
    "RestConnectorBase",
    "RestConnectorConfig",
    "RestPaginationConfig",
    "RestPaginationMode",
    "RestPreparedRequest",
    "RestRetryPolicy",
    "RestRequestTemplate",
    "RestRequestWindow",
    "RestResolvedAuth",
    "RestResponse",
    "RestRunResult",
    "LocalRestConnector",
    "LocalSqlConnector",
    "SqlConnectionConfig",
    "SqlConnectionDriver",
    "SqlConnectorBase",
    "SqlConnectorConfig",
    "SqlExtractionMode",
    "SqlPreparedQuery",
    "SqlQueryResult",
    "SqlQueryTemplate",
    "SqlRunResult",
    "SqlWatermarkConfig",
    "SqlWatermarkSource",
]
