"""Optional integration boundaries for external platform tooling."""

from elt_pipeline.integrations.lineage import (
    LineageAdapter,
    LineageEmissionPolicy,
    LineageRemoteEmitter,
    OpenLineageHttpEmitter,
    build_lineage_adapter,
)
from elt_pipeline.integrations.metrics import (
    AlertHook,
    MetricsExporter,
    ObservabilityAdapter,
    ObservabilityPolicy,
    OtlpHttpTraceExporter,
    PrometheusRemoteWriteExporter,
    TraceExporter,
    WebhookAlertHook,
    build_observability_adapter,
)
from elt_pipeline.integrations.orchestration import (
    AirflowCliWrapper,
    CliInvocationRequest,
    CliInvocationResult,
    OrchestrationCliInvoker,
    OrchestrationMetadata,
    SubprocessCliInvoker,
    build_airflow_orchestration_metadata,
    load_orchestration_metadata_from_env,
)
from elt_pipeline.integrations.quality import (
    QualityCheckResult,
    QualityCheckStatus,
    QualityDatasetRef,
    QualityHookAdapter,
    QualityHookBackend,
    QualityHookPolicy,
    QualityHookRequest,
    QualityHookSummary,
    RowCountQualityHook,
    build_quality_hook,
    quality_error_already_recorded,
    raise_for_blocking_quality_failures,
)

__all__ = [
    "LineageAdapter",
    "LineageEmissionPolicy",
    "LineageRemoteEmitter",
    "OpenLineageHttpEmitter",
    "build_lineage_adapter",
    "AlertHook",
    "MetricsExporter",
    "ObservabilityAdapter",
    "ObservabilityPolicy",
    "OtlpHttpTraceExporter",
    "PrometheusRemoteWriteExporter",
    "TraceExporter",
    "WebhookAlertHook",
    "build_observability_adapter",
    "AirflowCliWrapper",
    "CliInvocationRequest",
    "CliInvocationResult",
    "OrchestrationCliInvoker",
    "OrchestrationMetadata",
    "SubprocessCliInvoker",
    "build_airflow_orchestration_metadata",
    "load_orchestration_metadata_from_env",
    "QualityCheckResult",
    "QualityCheckStatus",
    "QualityDatasetRef",
    "QualityHookAdapter",
    "QualityHookBackend",
    "QualityHookPolicy",
    "QualityHookRequest",
    "QualityHookSummary",
    "RowCountQualityHook",
    "build_quality_hook",
    "quality_error_already_recorded",
    "raise_for_blocking_quality_failures",
]
