schema_version: v1
environments:
  default:
    defaults: {}
sources:
  - name: local_files
    connector_type: object_storage
    entities:
      - name: orders
        extraction:
          bucket_path: examples/data/object_storage/orders
          payload_format: json
          sync_mode: full
      - name: shipments
        extraction:
          bucket_path: examples/data/object_storage/shipments
          payload_format: json
          sync_mode: full
